- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state:  latest

- name: Start and enable mysql service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled:  yes

- name: import role tasks
  tags: deployment
  ansible.builtin.import_role:
    name: commonforrallroles
    tasks_from: appcode
  notify:
    - restart nginx
    
- name: copy frontend config file using template module
  ansible.builtin.template:
    src:  expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - restart nginx

#if there is change in config then only we should restart the service
#- name: restart nginx
#  ansible.builtin.service:
#    name: nginx
#   state: restarted